// SKYLONZE in-app assistant.
//
// Two modes:
//  1. If ANTHROPIC_API_KEY is set, answers are generated by Claude with a
//     SKYLONZE-aware system prompt.
//  2. Otherwise a built-in, knowledge-based responder handles the common
//     questions so the assistant works fully offline / without a key.

export type ChatMessage = { role: "user" | "assistant"; content: string };

export const SYSTEM_PROMPT = `You are NOVA, the in-app assistant for SKYLONZE — a futuristic digital prediction-market platform.

Key facts about SKYLONZE:
- Users forecast real-world questions (crypto, stocks, sports, technology, startups, trending events, politics) by predicting YES or NO on markets.
- The platform currency is SKY-3030 ("SKY"). It is a VIRTUAL ecosystem currency — it is NOT real money and has no cash value. New users get 500 SKY after verifying their email.
- Predicting: open a market, pick YES or NO, and stake SKY. Minimum stake is 10 SKY. When an admin resolves the market, winners are paid their potential payout.
- Leaderboard: ranks forecasters by realized SKY profit. Badge tiers — Oracle (10+ settled, 100K+ profit, 70%+ accuracy), Sage (25K+ profit), Analyst (1+ settled forecast), Rookie (none yet).
- Startups: a showcase of companies you can "back" by allocating SKY (minimum 50 SKY) to express conviction.
- Wallet: shows your SKY balance, lets you send SKY to other users, and tracks every transaction. Buying SKY with real money is currently restricted to higher-rank users.
- Streaks: forecasting on consecutive days unlocks bonus SKY.
- Profile & Settings: edit your name, handle, password, and upload a profile picture.

Style: friendly, concise, and on-topic. Keep answers to a few sentences. Never give real financial or investment advice, and always remind users that SKY-3030 is a virtual currency when relevant. If asked something unrelated to SKYLONZE, gently steer back to the platform.`;

type Rule = { test: RegExp; reply: string };

const RULES: Rule[] = [
  {
    test: /\b(what is|about|explain).*(skylonze|this (site|platform|app))|^skylonze\b/i,
    reply:
      "SKYLONZE is a futuristic prediction-market platform. You forecast real-world questions across crypto, stocks, sports, tech, startups and trending events by predicting YES or NO using SKY-3030 — a virtual ecosystem currency (not real money). Win markets to climb the leaderboard and earn badges.",
  },
  {
    test: /\b(sky-?3030|sky coin|what.*sky\b|currency|coins?)\b/i,
    reply:
      "SKY-3030 (or just SKY) is SKYLONZE's virtual ecosystem currency — it has no real-world cash value. You get 500 SKY after verifying your email, then use it to make predictions and back startups.",
  },
  {
    test: /\b(how.*(predict|forecast|bet|stake)|make a prediction|place.*prediction)\b/i,
    reply:
      "To predict: open any market, choose YES or NO, and stake SKY (minimum 10). When an admin resolves the market, winners receive their potential payout straight to their wallet. Browse markets under 'Predict'.",
  },
  {
    test: /\b(leaderboard|rank|ranking|top forecasters?)\b/i,
    reply:
      "The leaderboard ranks forecasters by realized SKY profit from settled predictions. The top 10 appear in the ranking list, with the top 3 highlighted on the podium. Win markets to rise.",
  },
  {
    test: /\b(badge|tier|oracle|sage|analyst|rookie)\b/i,
    reply:
      "Badges are earned automatically: Rookie (no settled forecasts yet), Analyst (1+ settled forecast), Sage (25,000+ SKY profit), and Oracle (10+ settled forecasts, 100K+ SKY profit, and 70%+ accuracy). There's a full 'How badges work' guide on the Leaderboard page.",
  },
  {
    test: /\b(startup|back a|invest|backing)\b/i,
    reply:
      "On the Startups page you can 'back' companies you believe in by allocating SKY (minimum 50). Open a startup, hit Back, and choose an amount — it's deducted from your wallet and recorded as a transaction.",
  },
  {
    test: /\b(wallet|balance|send sky|transfer)\b/i,
    reply:
      "Your Wallet shows your SKY balance, full transaction history, and lets you send SKY to other users by their handle. You can also see lifetime earned and spent there.",
  },
  {
    test: /\b(buy|purchase).*(sky|coin)|real money|top ?up\b/i,
    reply:
      "Buying SKY with real money is currently available only to users with a higher rank, so the Buy SKY option on the Wallet is locked for now. You can still earn SKY by signing up, keeping streaks, and winning predictions.",
  },
  {
    test: /\b(streak|daily|bonus)\b/i,
    reply:
      "Make at least one forecast each day to build a streak. Streaks unlock escalating SKY bonuses and seasonal rewards — check the streak strip on your Dashboard.",
  },
  {
    test: /\b(verify|verification|email.*confirm|confirm.*email)\b/i,
    reply:
      "After signing up, verify your email to unlock predicting and claim your 500 SKY welcome bonus. Use the 'Resend email' banner if you didn't get the link. Admins can also verify accounts manually.",
  },
  {
    test: /\b(sign ?up|register|create.*(account|profile)|get started)\b/i,
    reply:
      "Tap 'Get started' to create an account with your name, a handle, email and password. Verify your email and you'll receive 500 SKY to begin forecasting.",
  },
  {
    test: /\b(profile|avatar|picture|photo|password|settings|change.*name)\b/i,
    reply:
      "Open your Profile to upload a photo (click your avatar) and review your stats and badges. Use Settings to update your name, handle, or password.",
  },
  {
    test: /\b(hi|hello|hey|yo|sup|good (morning|evening|afternoon))\b/i,
    reply:
      "Hey! I'm NOVA, your SKYLONZE assistant. Ask me about making predictions, the leaderboard, badges, backing startups, your wallet, or SKY-3030.",
  },
  {
    test: /\b(help|what can you|options|menu)\b/i,
    reply:
      "I can help with: making predictions, how SKY-3030 works, the leaderboard & badges, backing startups, your wallet & transfers, streaks, and account/verification. What would you like to know?",
  },
  {
    test: /\b(thank|thanks|cheers|appreciate)\b/i,
    reply: "Anytime! Good luck out there on the markets. 🔮",
  },
];

export function localReply(message: string): string {
  const text = (message || "").trim();
  if (!text) return "Ask me anything about SKYLONZE — predictions, SKY-3030, the leaderboard, startups, or your wallet.";
  for (const r of RULES) if (r.test.test(text)) return r.reply;
  return "I'm NOVA, the SKYLONZE assistant. I can explain how to make predictions, how SKY-3030 and the wallet work, the leaderboard and badge tiers, or how to back startups. Could you rephrase your question around one of those?";
}

/** Calls the Anthropic Messages API. Throws if the key is missing or the call fails. */
export async function claudeReply(messages: ChatMessage[]): Promise<string> {
  const key = process.env.ANTHROPIC_API_KEY;
  if (!key) throw new Error("No ANTHROPIC_API_KEY");
  const model = process.env.CHAT_MODEL || "claude-haiku-4-5-20251001";

  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "x-api-key": key,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model,
      max_tokens: 400,
      system: SYSTEM_PROMPT,
      messages: messages.slice(-12).map((m) => ({ role: m.role, content: m.content })),
    }),
  });

  if (!res.ok) {
    const detail = await res.text().catch(() => "");
    throw new Error(`Anthropic API error ${res.status}: ${detail.slice(0, 200)}`);
  }
  const data: any = await res.json();
  const text = Array.isArray(data?.content)
    ? data.content.filter((b: any) => b.type === "text").map((b: any) => b.text).join("\n").trim()
    : "";
  if (!text) throw new Error("Empty response");
  return text;
}
